name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'
      release_notes:
        description: 'Custom release notes (optional)'
        required: false
        type: string

jobs:
  release:
    uses: CarSharing/.github/workflows/version-bump.yml@main
    with:
      bump_type: ${{ inputs.bump_type }}
      package_manager: 'npm'  # or 'yarn', 'pnpm'
      working_directory: '.'   # change if package.json is in a subdirectory
      create_release: true
      release_notes: ${{ inputs.release_notes }}
    secrets: inherit