name: Bump Version and Tag Release

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Select deployment target"
        required: true
        type: choice
        options:
          - production    # maps to main branch
          - staging      # maps to staging branch  
          - development  # maps to dev/latest branch
          - hotfix       # maps to hotfix/* branch
        default: "production"
      bump_type:
        description: "Type of version bump"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"
      release_notes:
        description: "Custom release notes (optional)"
        required: false
        type: string
        default: ""

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  map-target:
    name: Map Deployment Target
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.mapping.outputs.branch }}
      environment: ${{ steps.mapping.outputs.environment }}
      tag_suffix: ${{ steps.mapping.outputs.tag_suffix }}
    steps:
      - name: Map deployment target to branch and environment
        id: mapping
        run: |
          case "${{ inputs.deployment_target }}" in
            "production")
              echo "branch=main" >> $GITHUB_OUTPUT
              echo "environment=production" >> $GITHUB_OUTPUT
              echo "tag_suffix=-chevron" >> $GITHUB_OUTPUT  # No suffix for production
              ;;
            "staging")
              echo "branch=staging" >> $GITHUB_OUTPUT
              echo "environment=staging" >> $GITHUB_OUTPUT
              echo "tag_suffix=-staging" >> $GITHUB_OUTPUT
              ;;
            "development")
              echo "branch=dev/latest" >> $GITHUB_OUTPUT
              echo "environment=development" >> $GITHUB_OUTPUT
              echo "tag_suffix=-dev" >> $GITHUB_OUTPUT
              ;;
            "hotfix")
              echo "branch=hotfix" >> $GITHUB_OUTPUT
              echo "environment=hotfix" >> $GITHUB_OUTPUT
              echo "tag_suffix=-hotfix" >> $GITHUB_OUTPUT
              ;;
          esac

  release:
    name: Bump Version and Create Release
    needs: map-target
    uses: berzhavycha/CarSharing/.github/workflows/version-bump.yml@main
    with:
      bump_type: ${{ inputs.bump_type }}
      target_branch: ${{ needs.map-target.outputs.branch }}
      environment: ${{ needs.map-target.outputs.environment }}
      tag_suffix: ${{ needs.map-target.outputs.tag_suffix }}
      package_manager: "yarn"
      working_directory: "."
      create_release: true
      release_notes: ${{ inputs.release_notes }}
    secrets: inherit