name: Version Bump and Tag

on:
  workflow_call:
    inputs:
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        type: string
      package_manager:
        description: 'Package manager to use (npm, yarn, pnpm)'
        required: false
        type: string
        default: 'npm'
      working_directory:
        description: 'Working directory where package.json is located'
        required: false
        type: string
        default: '.'
      create_release:
        description: 'Whether to create a GitHub release'
        required: false
        type: boolean
        default: true
      release_notes:
        description: 'Custom release notes'
        required: false
        type: string
        default: ''
    outputs:
      new_version:
        description: 'The new version that was created'
        value: ${{ jobs.bump-version.outputs.new_version }}
      tag_name:
        description: 'The git tag that was created'
        value: ${{ jobs.bump-version.outputs.tag_name }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      tag_name: ${{ steps.version.outputs.tag_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: ${{ inputs.package_manager }}
          cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Validate bump type
        run: |
          if [[ ! "${{ inputs.bump_type }}" =~ ^(major|minor|patch)$ ]]; then
            echo "Error: bump_type must be one of: major, minor, patch"
            exit 1
          fi

      - name: Get current version
        id: current_version
        working-directory: ${{ inputs.working_directory }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Bump version
        id: version
        working-directory: ${{ inputs.working_directory }}
        run: |
          # Bump version based on type
          case "${{ inputs.bump_type }}" in
            "major")
              NEW_VERSION=$(npm version major --no-git-tag-version)
              ;;
            "minor")
              NEW_VERSION=$(npm version minor --no-git-tag-version)
              ;;
            "patch")
              NEW_VERSION=$(npm version patch --no-git-tag-version)
              ;;
          esac
          
          # Remove 'v' prefix from npm version output
          NEW_VERSION=${NEW_VERSION#v}
          TAG_NAME="v$NEW_VERSION"
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"
          echo "Tag name: $TAG_NAME"

      - name: Commit version bump
        working-directory: ${{ inputs.working_directory }}
        run: |
          git add package.json
          if [ -f package-lock.json ]; then
            git add package-lock.json
          fi
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }} (${{ inputs.bump_type }})"

      - name: Create and push tag
        run: |
          git tag ${{ steps.version.outputs.tag_name }}
          git push origin HEAD --tags

      - name: Generate release notes
        id: release_notes
        if: inputs.create_release
        run: |
          if [ -n "${{ inputs.release_notes }}" ]; then
            NOTES="${{ inputs.release_notes }}"
          else
            # Generate automatic release notes based on commits since last tag
            LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
            if [ -n "$LAST_TAG" ]; then
              NOTES="## Changes since $LAST_TAG"$'\n\n'
              NOTES+=$(git log --pretty=format:"- %s (%h)" $LAST_TAG..HEAD)
            else
              NOTES="## Changes in this release"$'\n\n'
              NOTES+=$(git log --pretty=format:"- %s (%h)" --max-count=10)
            fi
          fi
          
          # Escape newlines for GitHub Actions
          NOTES="${NOTES//'%'/'%25'}"
          NOTES="${NOTES//$'\n'/'%0A'}"
          NOTES="${NOTES//$'\r'/'%0D'}"
          
          echo "notes=$NOTES" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: inputs.create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          release_name: Release ${{ steps.version.outputs.tag_name }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false

      - name: Summary
        run: |
          echo "## Version Bump Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Previous Version:** ${{ steps.current_version.outputs.current_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **New Version:** ${{ steps.version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Bump Type:** ${{ inputs.bump_type }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag Created:** ${{ steps.version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Created:** ${{ inputs.create_release }}" >> $GITHUB_STEP_SUMMARY